### ISSUE TITLE
syntax error for := operator 

### ISSUE THREAD

**Issue by Jeff-groundcloud** [ravenkls/Maze-Generator-and-Solver#3]
love this work and just trying to implement it myself to learn. I am not familiar with the := operator and am getting the following error when running the project. any thoughts? 

Saw your work on reddit very cool! 

Traceback (most recent call last):
  File "dijkstra.py", line 10, in <module>
    from maze_analyser import Node, nodes_from_maze
  File "/Users/jeffreyeul/Maze-Generator-and-Solver/maze_analyser.py", line 92
    if node := nodes.get((x, y)):
             ^
SyntaxError: invalid syntax

**Comment by arovesto** [comment]
Are you using python [3.8+](https://www.python.org/dev/peps/pep-0572/) ?

**Comment by Jeff-groundcloud** [comment]
Yes installed 3.8 on a virtual environment. I found the := syntax documentation it looks like a compacted version of the if statement I am starting to understand but still unsure why I’m getting the error.

**Comment by ravenkls** [comment]
You're getting the syntax error because you're not running Python 3.8. The := operator was introduced in that version.

https://docs.python.org/3/whatsnew/3.8.html

If you have multiple Python versions installed, try typing 
`py -3.8 __main__.py` to run the program instead of `python __main__.py`

**Comment by arovesto** [comment]
perhaps it is really caused by python version. If in your traceback arrow above SyntaxError message is point to the ":=" operator it is probably that your python doesn't understand what ":=" is. You can probably change code in maze_analyser.py to 
```
node = nodes.get((x, y))
if node is not None:
    ...
``` 
to avoid this issue, because ":=" is used only once in codebase as far as I can see.
P. S.
@ravenkls can consider to do this, for compatibility reasons:)

**Comment by Jeff-groundcloud** [comment]
Thanks for the help team, sure enough I had my pyenv mapped to 3.5 and did not realize the := syntax was new.
